### ISSUE TITLE
[Question] Is a 1.20.4 update is planned ?

### ISSUE THREAD

**Issue by Anonyku05** [z3n01d/man-from-the-fog-reimagined#1]

**Comment by zenolth** [comment]
Yes I do, but only after the mod gets fully released and I stop adding much content, but I would first update to 1.20.2 and then 20.3 and so on and so on. (Even after I make ports for those versions, my primary focus will be 1.20.1)
Also, ask these types of questions in the Discord server, Github Issues are only for bugs, crashes etc.
