### ISSUE TITLE
[Question] Is it ok to fork this repository and conifgure some attributes about man?

### ISSUE THREAD

**Issue by Stilt1234** [z3n01d/man-from-the-fog-reimagined#12]
Hi, i was adding this mod to my server and i was wondering if i could fork this repo. I couldnt find any config file so i ended up coming here.

**Comment by zenolth** [comment]
You use gamerules to configure this mod.

**Comment by zenolth** [comment]
All gamerules for MFTFR are prefixed with man

**Comment by zenolth** [comment]
But if you want to change some specifics (The Man's speed, damage etc.) then feel free to fork this mod, just don't violate the license.
