### ISSUE TITLE
1.21.3

### ISSUE THREAD

**Issue by ghost** [z3n01d/man-from-the-fog-reimagined#14]

**Comment by zenolth** [comment]
Since 1.21.x has introduced drastical changes to Minecraft's codebase, I won't be upgrading to 1.20.5 or higher ***yet***.

**Comment by ghost** [comment]
> Since 1.21.x has introduced drastical changes to Minecraft's codebase, I won't be upgrading to 1.20.5 or higher _**yet**_.

Okay, you're still planning on doing it at some point right?

**Comment by zenolth** [comment]
When the mod is 100% completed, I'll slowly update from 1.20.1 to 1.21.x if possible.
