### ISSUE TITLE
Is there a way to disable the replacement of Minecraft's logo and edition?

### ISSUE THREAD

**Issue by mpustovoi** [z3n01d/man-from-the-fog-reimagined#4]
Why is it here? 
![minecraft](https://github.com/user-attachments/assets/11396b37-5ca2-46fd-a2af-93fcaa09a2b6)
![edition](https://github.com/user-attachments/assets/6fe5cf29-6a39-4162-a1d7-1433df4c6980)
It takes all the attention and there is absolutely no way to disable it.

**Comment by zenolth** [comment]
I think you should be able to just put the Fabric Mods resource pack below Minecraft's default to get the default main menu

**Comment by mpustovoi** [comment]
This is a crutch solution that is likely to lead to an absolute collapse for all mods that change the default behavior of Minecraft, starting with Sodium and ending with mods that make minor interface changes.
I suppose the only option would be to delete the files via archiver program.

**Comment by zenolth** [comment]
I'll think about removing it in the next update.
