### ISSUE TITLE
Cconfigurable Spawning

### ISSUE THREAD

**Issue by 533kr** [z3n01d/man-from-the-fog-reimagined#6]
I love a good spooky creature, but I recommend coding in some spawn configuration options--a lot of people, myself included, would prefer the Man(tm) spawn more rarely to keep things fresh and unpredictable. Also, if possible, an option to prevent spawn for a given period on new worlds would be lovely, as being slaughtered repeatedly on night one is not ideal.

**Comment by zenolth** [comment]
There are several gamerules prefixed with `man` that allow you to configure The Man's spawning behavior
